In [1]:
import uuid
import numpy as np

In [2]:
class Node:
    def __init__(self, tensor):
        self.tensor = tensor
        self.grad = None
        self.operation = None
#         self.parent_node = None
        self.previous_nodes = None
        self.tag = str(uuid.uuid4())
    
    def __repr__(self):
        return 'Node: ' + self.tag
    
    def __str__(self):
        return 'Node: ' + self.tag

In [ ]:
def copy_node(node):
    """
    copy node while keeping tensors same
    """
    new_node = Node(node.tensor)
    
    if node.previous_nodes is None:
        return new_node
    else:
        q = list()
        q.append(new_node)
        p = new_node
        p1 = p.previous_nodes[0]
        p2 = p.previous_nodes[1]
        while q:
            node_ = q.pop(0)
            n1, n2 = node_.previous_nodes
            new_n1 = Node(n1.tensor)
            new_n2 = Node(n2.tensor)
            n1.tensor.nodes.append(new_n1)
            n2.tensor.nodes.append(new_n2)
            
            
    
    
    q = list()
    q.append(node)
    while q:
        node_ = q.pop(0)
        if node_.previous_nodes:
            n1, n2 = node_.previous_nodes
            new_node.
        
    return new_node

In [3]:
class Tensor:
    """
    Tensor
    """
    def __init__(self, numpy_array):
        if not isinstance(numpy_array, np.ndarray):
            raise ValueError("Must be initialized with a Numpy array")
        self.value = numpy_array
        self.nodes = list()
        self.operation = None  # type of operation done to create this node.
        self.node = Node(self)
        
    def backward(self):
        self._compute_grads(self.nodes[-1])
        
    def get_grad(self):
        return sum([n.grad for n in self.nodes])
    
    def _compute_grads(self, node):
        if node.grad is None:
            node.grad = np.full(node.tensor.value.shape, 1)
        
        if node.previous_nodes is None:
            return
        else:
            n1, n2 = node.previous_nodes
            
            if node.operation == 'add':
                n1.grad = np.copy(node.grad)
                n2.grad = np.copy(node.grad)
            elif node.operation == 'mul':
                n1.grad = np.copy(node.grad) * np.copy(n2.tensor.value)
                n2.grad = np.copy(node.grad) * np.copy(n1.tensor.value)
            else:
                raise ValueError("Invalid operation: {}".format(str(node.operation)))
            # tensor.grad = None  # remove for saving memory
            self._compute_grads(n1)
            self._compute_grads(n2)
    
    def _add_tensor(self, other):
        """
        Tensor addition (core)
        """
        if isinstance(other, Tensor):
            # check shapes
            if not self.value.shape == other.value.shape:
                raise ValueError("Tensors must have the same shape. shape1: {}, shape2: {}".\
                                     format(str(self.value.shape), str(other.value.shape)))
            operation_result = self.value + other.value
            
            # tensor
            new_tensor = Tensor(operation_result)
            new_tensor.operation = 'add'
            
            if self == other:
                print('same')
                other_node = Node(other)  # generate a new node
                other_node.previous_nodes = self.node.previous_nodes
                if self.node not in self.nodes:
                    self.nodes.append(self.node)
                if other_node not in self.nodes:
                    self.nodes.append(other_node)
            else:
                other_node = other.node
                self.nodes.append(self.node)
            
            new_tensor.node.operation = 'add'
            new_tensor.node.previous_nodes = [self.node, other_node]
            new_tensor.nodes.append(new_tensor.node)
            
            
#             # node
#             if self.node is None:
#                 self_node = Node(self)
#                 self.node = self_node
#             else:
#                 self_node = self.node
#             other_node = Node(other)
#             new_node = Node(new_tensor)
#             new_node.operation = 'add'
#             self_node.parent_node = new_node
#             other_node.parent_node = new_node
#             new_node.previous_nodes = [self_node, other_node]
            
#             other.node = other_node
#             new_tensor.node = new_node
            
            
#             # couple tensor-node
#             if self_node not in self.nodes:
#                 self.nodes.append(self_node)
#             else:
#                 print(self.nodes)
#                 raise ValueError("Something is wrong. (self)")
                
#             if other_node not in other.nodes:
#                 other.nodes.append(other_node)
#             else:
#                 raise ValueError("Something is wrong. (other)")
            
#             if new_node not in new_tensor.nodes:
#                 new_tensor.nodes.append(new_node)
#             else:
#                 raise ValueError("Something is wrong. (new_node)")
            
            return new_tensor
        else:
            raise ValueError("Operands must be of `Tensor` type.")
    
    def _mul_tensor(self, other):
        """
        Tensor multiplication (core)
        """
        if isinstance(other, Tensor):
            # check shapes
            if not self.value.shape == other.value.shape:
                raise ValueError("Tensors must have the same shape. shape1: {}, shape2: {}".\
                                     format(str(self.value.shape), str(other.value.shape)))
            operation_result = self.value * other.value
            
            # tensor
            new_tensor = Tensor(operation_result)
            new_tensor.operation = 'mul'
            
            # node
            if self.node is None:
                self_node = Node(self)
                self.node = self_node
            else:
                self_node = self.node
            other_node = Node(other)
            new_node = Node(new_tensor)
            new_node.operation = 'mul'
            self_node.parent_node = new_node
            other_node.parent_node = new_node
            new_node.previous_nodes = [self_node, other_node]
            
            other.node = other_node
            new_tensor.node = new_node
            
            # couple tensor-node
            if self_node not in self.nodes:
                self.nodes.add(self_node)
            else:
                print(self.nodes)
                raise ValueError("Something is wrong. (self)")
                
            if other_node not in other.nodes:
                other.nodes.add(other_node)
            else:
                raise ValueError("Something is wrong. (other)")
            
            if new_node not in new_tensor.nodes:
                new_tensor.nodes.add(new_node)
            else:
                raise ValueError("Something is wrong. (new_node)")
            
            return new_tensor
        else:
            raise ValueError("Operands must be of `Tensor` type.")
            
    def _convert_other_to_tensor(self, other):
        """
        Convert 'other' to Tensor with proper shape for 
        proper operation.
        """
        # convert other to Tensor
        if isinstance(other, int) or isinstance(other, float):
            t = Tensor(np.full(self.value.shape, other))
        elif isinstance(other, np.ndarray):
            other = np.broadcast_to(other, self.value.shape)
            t = Tensor(other)
        elif isinstance(other, Tensor):
            t = other  # no need to do anything
        else:
            raise ValueError("Invalid type")
        return t
    
    def __add__(self, other):
        print('add is called')
        # convert other to tensor
        t = self._convert_other_to_tensor(other)
        # do tensor addition
        return self._add_tensor(t)
    
    def __radd__(self, other):
        print('radd is called')
        return self.__add__(other)
            
    def __mul__(self, other):
        # convert other to tensor
        t = self._convert_other_to_tensor(other)
        # do tensor multiplication
        return self._mul_tensor(t)
    
    def __rmul__(self, other):
        pass
        
    def __sub__(self, other):
        # convert other to tensor
        t = self._convert_other_to_tensor(other * (-1))
        # do tensor addition
        return self._add_tensor(t)
    
    def __str__(self):
        r = self.value.__repr__()
        r = r.replace('array', 'Tensor')
        return r
    
    def __repr__(self):
        r = self.value.__repr__()
        r = r.replace('array', 'Tensor')
        return r

In [4]:
arr1 = np.random.rand(2, 3)
# arr2 = np.random.rand(2, 3)

In [5]:
t1 = Tensor(arr1)
# t2 = Tensor(arr2)
print('t1:', t1)
# print('t2:', t2)

t1: Tensor([[0.4424587 , 0.03064619, 0.89818591],
       [0.9982628 , 0.35451074, 0.36915921]])


In [6]:
t5 = t1 + t1 + 2
t6 = t5 + t5

add is called
same
add is called
add is called
same


In [10]:
t5.nodes[1].previous_nodes

[Node: 1147979e-8e4a-4414-ae67-fe8aa2d186b6,
 Node: 81127dee-5b83-4c72-bf3f-6c8e306c5c35]

In [7]:
t6.backward()

In [8]:
t5.nodes

[Node: 623f5d84-a200-42b2-8f1d-6a5b6661d92a,
 Node: 623f5d84-a200-42b2-8f1d-6a5b6661d92a,
 Node: a239bd41-0c48-4ddf-9240-897c7d0a0855]

In [12]:
t6.nodes[0].previous_nodes[0].previous_nodes  

[Node: f74ec4b2-6531-44b6-9193-510a36220949,
 Node: ada811d7-bc7d-41e0-9a9c-47934be32234]

In [13]:
t1.nodes

[Node: 2cb89e6e-bdde-4503-8e2d-5fe0f4cdae8d,
 Node: b3b4d479-683b-46d7-926f-0a1c4ee87d88]

In [14]:
t5.node

Node: 623f5d84-a200-42b2-8f1d-6a5b6661d92a

In [8]:
t1.nodes

[Node: 0019ccc3-afbb-4e8c-b856-cb786bfe07c6,
 Node: e4b90f13-31f0-43c9-bd9c-bfb84a37911e]

In [10]:
t1.nodes[2].previous_nodes

In [11]:
t5.nodes[0].previous_nodes[0].previous_nodes

In [24]:
[n.grad for n in t1.nodes]

[None, None, array([[1, 1, 1],
        [1, 1, 1]])]

In [25]:
[n for n in t1.nodes]

[Node: bee201f0-f8ac-4a79-987c-2870f4fbf992,
 Node: cc559bc2-5449-4e2b-9432-cc661cff3f53,
 Node: db6908c4-35be-44e7-8f71-ec569acfbff9]

In [10]:
t1.nodes

[Node: 36e81509-e986-46a2-bc94-4018b688353f,
 Node: c54c01a1-599c-43de-bf29-4fc489da0b95,
 Node: 487a8c07-71a4-405a-9fe3-b63d33456e28]

In [8]:
[n.grad for n in t1.nodes]

[None, None, array([[1, 1, 1],
        [1, 1, 1]])]

In [12]:
[n.operation for n in t1.nodes]

[None, None, None]

In [10]:
t1.nodes

[Node: a17fbe70-f02f-497d-b20a-dc9ea9690a5b,
 Node: caf038f8-b6b8-473d-87b4-57799f93b1e8,
 Node: 13ff6616-f09e-4583-97cc-edc58c5187b5]

In [19]:
t5.nodes[0].previous_nodes[1].operation

In [5]:
t10 = (t1 - 2) * (t1 - 2)

In [6]:
t10.backward()

In [7]:
t1.grad

array([[-2.99519256, -3.70566587, -3.57598042],
       [-2.62173808, -2.41002425, -2.09688913]])

In [11]:
(2 * t1) - 4

Tensor([[-1.49759628, -1.85283293, -1.78799021],
       [-1.31086904, -1.20501212, -1.04844457]])

In [14]:
t1 + 2

Tensor([[2.50240372, 2.14716707, 2.21200979],
       [2.68913096, 2.79498788, 2.95155543]])

In [47]:
t10 = (t1 + 2) / (t1 + 2)

TypeError: unsupported operand type(s) for /: 'Tensor' and 'Tensor'

In [44]:
t10.backward()

In [45]:
t1.grad

array([[5.52619492, 4.71267724, 5.95470321],
       [4.45144276, 4.1928202 , 5.00457934]])

In [46]:
2 * arr1 + 4

array([[5.52619492, 4.71267724, 5.95470321],
       [4.45144276, 4.1928202 , 5.00457934]])

In [6]:
t20.backward()

NameError: name 't20' is not defined

In [ ]:
t1.grad

In [6]:
import torch

In [7]:
t = torch.rand(2, 3)
t

tensor([[0.8264, 0.3591, 0.8097],
        [0.5179, 0.3105, 0.6348]])

In [9]:
a = 'txt_another'

In [11]:
a.replace('txt', 'some')

'some_another'