In [1]:
import torch

In [2]:
t1 = torch.rand(2, 3, requires_grad=True)
t1

tensor([[0.1120, 0.2378, 0.9129],
        [0.7379, 0.8068, 0.0403]], requires_grad=True)

In [3]:
t2 = t1 ** (1.234)

In [5]:
t2.mean().backward()

In [7]:
t1.grad

tensor([[0.1667, 0.1667, 0.1667],
        [0.1667, 0.1667, 0.1667]])

In [8]:
1/6.0

0.16666666666666666

In [4]:
t3.backward()

In [5]:
t1.grad

tensor([[0.5000, 0.5000, 0.5000],
        [0.5000, 0.5000, 0.5000]])

In [23]:
import numpy as np

In [41]:
class Tensor:
    """
    Tensor
    """
    def __init__(self, numpy_array):
        if not isinstance(numpy_array, np.ndarray):
            raise ValueError("Must be initialized with a Numpy array")
        self.value = numpy_array
        self.previous_tensors = None
        self.operation = None  # type of operation done to create this tensor.
        self.grad = None
        
    def backward(self):
        self._compute_grads(self)
    
    def _compute_grads(self, tensor):
        if tensor.grad is None:
            tensor.grad = np.full(self.value.shape, 1)
        
        if tensor.previous_tensors is None:
            return
        else:
            t1, t2 = tensor.previous_tensors
            if t1.grad is None:
                t1.grad = 0
            if t2.grad is None:
                t2.grad = 0
            
            if tensor.operation == 'add':
                t1.grad = t1.grad + tensor.grad
                t2.grad = t2.grad + tensor.grad
            elif tensor.operation == 'mul':
                t1.grad = t1.grad + tensor.grad * t2.value 
                t2.grad = t2.grad + tensor.grad * t1.value
            else:
                raise ValueError("Invalid operation")
            tensor.grad = None  # remove for saving memory
            self._compute_grads(t1)
            self._compute_grads(t2)
    
    def _add_tensor(self, other):
        """
        Tensor addition
        """
        if isinstance(other, Tensor):
            # check shapes
            if not self.value.shape == other.value.shape:
                raise ValueError("Tensors must have the same shape. shape1: {}, shape2: {}".\
                                     format(str(self.value.shape), str(other.value.shape)))
            operation_result = self.value + other.value
            new_tensor = Tensor(operation_result)
            new_tensor.operation = 'add'
            new_tensor.previous_tensors = [self, other]
            return new_tensor
        else:
            raise ValueError("Operands must be of `Tensor` type.")
    
    def _mul_tensor(self, other):
        """
        Tensor multiplication
        """
        if isinstance(other, Tensor):
            # check shapes
            if not self.value.shape == other.value.shape:
                raise ValueError("Tensors must have the same shape. shape1: {}, shape2: {}".\
                                     format(str(self.value.shape), str(other.value.shape)))
            operation_result = self.value * other.value
            new_tensor = Tensor(operation_result)
            new_tensor.operation = 'mul'
            new_tensor.previous_tensors = [self, other]
            return new_tensor
        else:
            raise ValueError("Operands must be of `Tensor` type.")
            
    def _convert_other_to_tensor(self, other):
        """
        Convert 'other' to Tensor with proper shape for 
        proper operation.
        """
        # convert other to Tensor
        if isinstance(other, int) or isinstance(other, float):
            t = Tensor(np.full(self.value.shape, other))
        elif isinstance(other, np.ndarray):
            other = np.broadcast_to(other, self.value.shape)
            t = Tensor(other)
        elif isinstance(other, Tensor):
            t = other  # no need to do anything
        else:
            raise ValueError("Invalid type")
        return t
    
    def __add__(self, other):
        # convert other to tensor
        t = self._convert_other_to_tensor(other)
        # do tensor addition
        return self._add_tensor(t)
        
    def __mul__(self, other):
        # convert other to tensor
        t = self._convert_other_to_tensor(other)
        # do tensor multiplication
        return self._mul_tensor(t)
            
    def __str__(self):
        return self.value.__repr__()

In [42]:
arr1 = np.random.rand(2, 3)
arr2 = np.random.rand(2, 3)

In [43]:
t1 = Tensor(arr1)
t2 = Tensor(arr2)
print('t1:', t1)
print('t2:', t2)

t1: array([[0.49488168, 0.39656946, 0.11092324],
       [0.32086915, 0.10195837, 0.72973021]])
t2: array([[0.42850598, 0.13328499, 0.49256551],
       [0.47318013, 0.75443311, 0.67679708]])


In [44]:
t10 = t1 * 2
t11 = (t1 + 2) * 3
t20 = t10 + t11

In [33]:
t3 = t1 * 2

In [34]:
t3.backward()

In [35]:
t1.grad

array([[2, 2, 2],
       [2, 2, 2]])

In [31]:
t5 = t1 * 2

In [32]:
t5.backward()

In [33]:
t1.grad

array([[2, 2, 2],
       [2, 2, 2]])

In [5]:
t3 = Tensor(np.full(arr1.shape, 10)) * t1 * Tensor(np.full(arr1.shape, 5)) * Tensor(np.full(arr1.shape, 5)) + t2 * Tensor(np.full(arr1.shape, 3))
t4 = (t3 + Tensor(np.full(arr1.shape, 2))) * Tensor(np.full(arr1.shape, 7))

In [6]:
t4.backward()

In [7]:
t1.grad

array([[1750, 1750, 1750],
       [1750, 1750, 1750]])

In [8]:
t2.grad

array([[21, 21, 21],
       [21, 21, 21]])