In [1]:
import numpy as np

In [18]:
class Tensor:
    """
    Tensor
    """
    def __init__(self, numpy_array):
        self.value = numpy_array
        self.previous_tensor = None
        self.operation = None
        self.grad = None
        
    def backward(self):
        p_ahead = self
        p = self.previous_tensor
        grad = None
        while p is not None:
            if p.operation[0] == 'add':
                if grad is None:
                    grad = 1
                else:
                    grad = grad
            elif p.operation[0] == 'sub':
                if grad is None:
                    grad = 1
                else:
                    grad = grad
            elif p.operation[0] == 'rsub':
                if grad is None:
                    grad = -1
                else:
                    grad = grad * -1
            elif p.operation[0] == 'mul':
                if grad is None:
                    grad = p.operation[1]
                else:
                    grad = grad * p.operation[1]
            else:
                raise ValueError("Unknown operation")
            print('grad:', grad)
            p = p.previous_tensor
            p_ahead = p_ahead.previous_tensor
        p_ahead.grad = grad
        
    def __add__(self, other):
        self.operation = ('add', other)
        operation_result = self.value + other
        new_tensor = Tensor(numpy_array=operation_result)
        new_tensor.previous_tensor = self
        return new_tensor
    
    def __radd__(self, other):
        return self.__add__(other)
    
    def __sub__(self, other):
        self.operation = ('sub', other)
        operation_result = self.value - other
        new_tensor = Tensor(numpy_array=operation_result)
        new_tensor.previous_tensor = self
        return new_tensor
        
    def __rsub__(self, other):
        self.operation = ('rsub', other)
        operation_result = other - self.value
        new_tensor = Tensor(numpy_array=operation_result)
        new_tensor.previous_tensor = self
        return new_tensor
    
    def __mul__(self, other):
        self.operation = ('mul', other)
        operation_result = self.value * other
        new_tensor = Tensor(numpy_array=operation_result)
        new_tensor.previous_tensor = self
        return new_tensor
    
    def mean(self):
        pass
    
    def __str__(self):
        return self.value.__repr__()

In [19]:
arr = np.ones((2, 3))
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [20]:
t = Tensor(arr)
t

In [21]:
t2 = t * 2

In [22]:
t3 = t2 * 3

In [23]:
t3.backward()

grad: 3
grad: 6


In [27]:
t3.grad is None

True

In [48]:
import torch

In [49]:
a = torch.ones(2, 3, requires_grad=True)
a

tensor([[1., 1., 1.],
        [1., 1., 1.]], requires_grad=True)

In [50]:
b = a * 1
for _ in range(3):
    b = b * 2

In [51]:
b = b.mean()

In [52]:
b.backward()

In [53]:
a.grad

tensor([[1.3333, 1.3333, 1.3333],
        [1.3333, 1.3333, 1.3333]])